### ISSUE TITLE
Losing landscape when printing

### ISSUE THREAD

**Issue by scottctr** [yWorks/jsPDF#21]
My PDFs are mostly working well, but in Adobe Print Preview it shows as Portrait instead of Landscape and it cuts off the right side of my pages. The pages look fine before opening print preview. Am I missing a setting? I just want all of the pages to be 11 x 8.5 inches (i.e. landscape mode of standard US paper).

```
const jsPdf = new jsPDF('l', 'pt', [pdfPageWidthPx, pdfPageHeightPx], { orientation: 'landscape', unit: 'px', format: [pdfPageWidthPx, pdfPageHeightPx], compress: true });
...snip....
jsPdf.addPage([Defaults.PdfPageWidthPx, Defaults.PdfPageHeightPx], 'landscape');
```

![image](https://user-images.githubusercontent.com/29161665/58129450-6261a280-7bdf-11e9-8d66-a34635480ab0.png)

**Comment by HackbrettXXX** [comment]
As far as I know there is no property in the PDF format that sets the orientation for printing. In my Acrobat reader there is an "Auto portrait/landscape" option which is selected by default and correctly sets the orientation to landscape for me.
