### ISSUE TITLE
Dependency of canvg

### ISSUE THREAD

**Issue by ThomasJunk** [yWorks/jsPDF#25]
I know this version is meant to be compatible to upstream.
OTOH, this version is used together with svg2pdf.
For the workings of svg2pdf the dependency to `canvg` is not necessary. 
Is it here for compatibiliy reasons or could it be removed?

**Comment by HackbrettXXX** [comment]
You are right. It is not required for svg2pdf to work, but we want to stay compatible to upstream, which is why we will keep the dependency. If you're using jsPDF only together with svg2pdf you do not need to load/bundle canvg. The same goes for html2canvas and stackblur-canvas.

**Comment by ThomasJunk** [comment]
Thanks for clarification.
