### ISSUE TITLE
Limit usage of embedded fonts to current used ones

### ISSUE THREAD

**Issue by ThomasJunk** [yWorks/jsPDF#29]
Hey guys,

MrRio JSDPF has an option putOnlyUsedFonts which limits the embedding of fonts to the actually used ones, which results in smaller PDFs - a goodie on Mobile with bad connection.

See: https://github.com/MrRio/jsPDF/blob/6c6ca0c4554eb5b6446dab9337befd6625119bee/src/jspdf.js#L86

Are there any current plans retrofitting this functionality into this fork?

I am asking only for planning purposes. If there is a foreseeable timeframe I would wait for it.

OTOH I could live without - so no actual pressure.

**Comment by HackbrettXXX** [comment]
Still the wrong project? ^^

**Comment by ThomasJunk** [comment]
> Still the wrong project? ^^

Hopefully not.
This is the jsPDF-fork, right?

(It's friday of a long week :D)

**Comment by HackbrettXXX** [comment]
Yes, this is the yWorks fork of jsPDF.

The feature you are referencing was already merged some time ago into this fork. So it should work. If not, this is a bug.

**Comment by ThomasJunk** [comment]
Oh. Okay.
I was lazy, using only https://github.com/yWorks/jsPDF/search?q=putOnlyUsedFonts&unscoped_q=putOnlyUsedFonts which currently shows this thread but not the code.

**Comment by ThomasJunk** [comment]
Okay. Looking at the source code, STRG+F finds it 3(.
I'll close here. Github's search is strange.
