### ISSUE TITLE
error after last release of 1.3

### ISSUE THREAD

**Issue by poplevente** [yWorks/jsPDF#7]
hey guys, 
after the release of version 1.3, i get the following error:

no such file or directory node_modules\jspdf-yworks\makeFonts.js

any info about this?

**Comment by HackbrettXXX** [comment]
Hi,

thanks for notifying us. I could reproduce it myself. The reason is probably that the `"makeFonts.js"` is missing from the package.json `"files"` entry. We're gonna fix this asap and upload a new version.

For now you'll probably need to use v1.2.70 or get v1.3.0 via Bower/GitHub.

**Comment by HackbrettXXX** [comment]
1.3.1 is now up and the error should be gone

**Comment by poplevente** [comment]
cool thanks!
